workflows: more checks and fail-fast: false

diff --git a/.github/workflows/build-vdrsternelec.yml b/.github/workflows/build-vdrsternelec.yml
--- a/.github/workflows/build-vdrsternelec.yml
+++ b/.github/workflows/build-vdrsternelec.yml
@@ -132,67 +132,89 @@ jobs:
               echo "| ${emo} | ${{ inputs.config }} | ${{ env.PROJECT }} | ${{ env.DEVICE }} | [${{ env.BRANCH }}@${{ env.REVISION }}](https://github.com/LibreELEC/LibreELEC.tv/tree/${{ env.REVISION }}) |" > build-summary-${{ inputs.config }}
           fi
           
-          # rename target files
-          if [ "$DISTRO" == "CoreELEC" ]; then
-              (
-                cd CoreELEC/target
-          
-                echo "============================="
-                echo " TEST: List target files"
-                echo "============================="
-                ls -laR .
-          
-                # release files
-                echo "=> CoreELEC release files"
-                for i in $(ls CoreELEC*{tar,img.gz,sha256}); do
-                  if [ -f $i ]; then
-                    NEWNAME=`echo $i | perl -pe "s/^(CoreELEC.*?)_(.*?)((_*.img.gz)|(\.tar))?(\.sha256)?$/VDR-\1-${{ inputs.releasetag }}\3\6/"`;
-                    echo "mv $i $NEWNAME"
-                    mv $i $NEWNAME || true;
-                  fi
-                done;          
-          
-                # addons
-                echo "=> CoreELEC addons"
-                if [ -d addons ]; then
-                  for i in $(find addons -name "*zip"); do
-                    if [ -f $i ]; then
-                      NACE=(${i//\// })
-                      echo "mv $i addons/CoreELEC-${NACE[1]}-${NACE[5]}"
-                      mv $i addons/CoreELEC-${NACE[1]}-${NACE[5]} || true
+          if [ ! ${{ env.BUILD_FAILED }} == 'true' ]; then          
+              # rename target files
+              if [ "$DISTRO" == "CoreELEC" ]; then
+                  (
+                    cd CoreELEC/target
+              
+                    echo "============================="
+                    echo " TEST: List target files"
+                    echo "============================="
+                    ls -laR .
+              
+                    # release files
+                    echo "=> CoreELEC release files"
+                    for i in $(ls CoreELEC*{tar,img.gz,sha256}); do
+                      if [ -f $i ]; then
+                        NEWNAME=`echo $i | perl -pe "s/^(CoreELEC.*?)_(.*?)((_*.img.gz)|(\.tar))?(\.sha256)?$/VDR-\1-${{ inputs.releasetag }}\3\6/"`;
+                        echo "mv $i $NEWNAME"
+                        mv $i $NEWNAME || true;
+                      fi
+                    done;          
+              
+                    # addons
+                    echo "=> CoreELEC addons"
+                    if [ -d addons ]; then
+                      for i in $(find addons -name "*zip"); do
+                        if [ -f $i ]; then
+                          NACE=(${i//\// })
+                          echo "mv $i addons/CoreELEC-${NACE[1]}-${NACE[5]}"
+                          mv $i addons/CoreELEC-${NACE[1]}-${NACE[5]} || true
+                        fi
+                      done
                     fi
-                  done
-                fi
-              )
+                  )
+              fi
+    
+              if [ "$DISTRO" == "LibreELEC.tv" ]; then          
+                  (
+                    cd LibreELEC.tv/target
+              
+                    # release files
+                    echo "=> LibreELEC release files"
+                    for i in `ls LibreELEC*{tar,img.gz,sha256}`; do
+                      if [ -f $i ]; then
+                        NEWNAME=`echo $i | perl -pe "s/^(LibreELEC.*?)-devel-\d+-.*?((-.*?)?(.img.gz)|(.tar))(\.sha256)?$/VDR-\1\3-${{ inputs.releasetag }}\4\5\6/"`;
+                        echo "mv $i $NEWNAME"
+                        mv $i $NEWNAME || true;
+                      fi
+                    done;
+              
+                    # addons
+                    echo "=> LibreELEC addons"
+                    if [ -d addons ]; then
+                      for i in $(find addons -name "*zip"); do
+                        if [ -f $i ]; then
+                          NACE=(${i//\// })
+                          echo "mv $i addons/LibreELEC-${NACE[1]}-${NACE[5]}"
+                          mv $i addons/LibreELEC-${NACE[1]}-${NACE[5]} || true
+                        fi
+                      done
+                    fi
+                  )
+              fi
           fi
+          
+          echo "BUILD_FAILED=$BUILD_FAILED" >> "$GITHUB_ENV"
 
-          if [ "$DISTRO" == "LibreELEC.tv" ]; then          
-              (
-                cd LibreELEC.tv/target
-          
-                # release files
-                echo "=> LibreELEC release files"
-                for i in `ls LibreELEC*{tar,img.gz,sha256}`; do
-                  if [ -f $i ]; then
-                    NEWNAME=`echo $i | perl -pe "s/^(LibreELEC.*?)-devel-\d+-.*?((-.*?)?(.img.gz)|(.tar))(\.sha256)?$/VDR-\1\3-${{ inputs.releasetag }}\4\5\6/"`;
-                    echo "mv $i $NEWNAME"
-                    mv $i $NEWNAME || true;
-                  fi
-                done;
-          
-                # addons
-                echo "=> LibreELEC addons"
-                if [ -d addons ]; then
-                  for i in $(find addons -name "*zip"); do
-                    if [ -f $i ]; then
-                      NACE=(${i//\// })
-                      echo "mv $i addons/LibreELEC-${NACE[1]}-${NACE[5]}"
-                      mv $i addons/LibreELEC-${NACE[1]}-${NACE[5]} || true
-                    fi
-                  done
-                fi
-              )
-          fi
+      - name: Save summary
+        uses: actions/upload-artifact@v4
+        with:
+          name: "build-summary-${{ inputs.config }}"
+          compression-level: 0
+          retention-days: 1
+          overwrite: true
+          if-no-files-found: ignore
+          path: |
+            build-summary-${{ inputs.config }}
+
+      - name: Check build
+        run: |
+            if [ ${{ env.BUILD_FAILED }} == 'true' ]; then
+                # abort this build
+                false
+            fi
 
       - name: Save release target files
         uses: actions/upload-artifact@v4
@@ -228,15 +250,3 @@ jobs:
           if-no-files-found: ignore
           path: |
             cef/cef*.zip
-
-      - name: Save summary
-        uses: actions/upload-artifact@v4
-        with:
-          name: "build-summary-${{ inputs.config }}"
-          compression-level: 0
-          retention-days: 1
-          overwrite: true
-          if-no-files-found: ignore
-          path: |
-            build-summary-${{ inputs.config }}
-            
